<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Miidle - Oops</title>
</head>
<body>
  <div style='margin: 4em auto; width: 347px;'>
  <img src='<?=BASEURI;?>/img/miidle_logo.png' />
  </div>
  <h1>Oops! Algo não saiu como esperado!</h1>
  <h2>Nossos cientistas malucos já foram notificados, mas se alguém perguntar, diga que ocorreu um erro do tipo "<?php echo $this->message ?>"</h2>

  <?php if (isset($this->exception)): ?>
  
  <h4>As informações da caixa abaixo podem ajudar os nossos técnicos a resolver o problema. Colabore copiando o conteúdo e colando no corpo de um e-mail para <a href='mailto:suporte@uemanet.uema.br'>suporte@uemanet.uema.br</a>.</h4>
  <div style='padding: 2em; border: 1px solid black; background-color: #f0f0f0;'>
  <p>
      <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Pilha de execução:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Parâmetros da requisição:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>
  </div>
  <?php endif ?>

</body>
</html>
